spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${spring.datasourse.url}
    username: ${spring.datasourse.username}
    password: ${spring.datasourse.password}
  data:
    mongodb:
      uri: ${spring.data.mongodb.uri}